# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$cmd_duration$directory $git_branch  $docker_context $python $cpp $lua $java $rust $c
$character
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[• ](bold fg:blue) "
error_symbol = "[• 󰅙](bold fg:red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: green"
symbol = "󰘬"
truncation_length = 4
truncation_symbol = ""
format = "• [](bold fg:green)[$symbol $branch(:$remote_branch)](fg:black bg:green)[ ](bold fg:green)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](blue)'
renamed = " ✍️ "
deleted = " 🗑 "

[hostname]
ssh_only = false
format =  "[•$hostname](bg:cyan bold fg:black)[](bold fg:cyan )"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed blue"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[](bold fg:cyan)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:blue fg:black"
truncation_length = 6
truncation_symbol = "••/"
format = '[](bold fg:blue)[$path ]($style)[](bold fg:blue)'


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "

[cmd_duration]
min_time = 0
format = '[](bold fg:yellow)[ $duration](bold bg:yellow fg:black)[](bold fg:yellow) •• '

[docker_context]
format = "via [$symbol$context]($style) "
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
disabled = false


[python]
symbol = " "
#pyenv_version_name = true
format = '[ $symbol ($version) ]($style)'
detect_extensions = ["py"]
python_binary = 'python3'
version_format = "v${raw}"



[cpp]
symbol = 'C++ '
disabled = false
format = '[$name $version]($style)'
detect_extensions	= ['cpp', 'cc', 'cxx', 'c++', 'hpp', 'hh', 'hxx', 'h++', 'tcc']


[java]
symbol = ""
format = '[ $symbol ($version) ]($style)'
disabled = false

[lua]
symbol = ""
format = '[ $symbol ($version) ]($style)'
disabled = false


[rust]
symbol = ""
format = '[ $symbol ($version) ]($style)'
disabled = false

[c]
symbol = ""
format = '[ $symbol ($version) ]($style)'
disabled = false
