FROM fbe-dockerreg.rwu.de/prj-iki-ros2/robots/tiago/tiago_base:sim-ir

RUN apt update

RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
RUN rm -rf /opt/nvim-linux-x86_64
RUN tar -C /opt -xzf nvim-linux-x86_64.tar.gz
ENV PATH="/opt/nvim-linux-x86_64/bin:$PATH"

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
  && apt-get install -y nodejs
RUN npm install -g npm@latest



RUN curl -LO https://go.dev/dl/go1.25.2.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.25.2.linux-amd64.tar.gz
ENV PATH="$PATH:/usr/local/go/bin"

RUN apt install  unzip -y


RUN curl -sS https://starship.rs/install.sh  | sh -s -- --yes

RUN curl https://sh.rustup.rs -sSf | sh  -s -- -y


RUN apt install exa -y

RUN apt install  wl-clipboard

RUN apt install ripgrep -y

# Addd  user
RUN apt install sudo -y
RUN groupadd -g 1000 niklas
RUN useradd  -u 1000 -g niklas  -g niklas -d /home/niklas/ -s /bin/bash niklas
# No password for user
RUN echo "niklas ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/niklas
USER niklas
WORKDIR /home/niklas

# Create directories
RUN mkdir -p /home/niklas/.config
RUN mkdir -p /home/niklas/ros2_ws/src

# Copy Config NVIM and common config
RUN sudo apt install git -y
RUN git clone https://github.com/xXFiEsTaDeAmOnXx/ros2_docker_configs.git
RUN mv ros2_docker_configs/.bashrc .
RUN touch .bash_history
RUN mv ros2_docker_configs/.config/* .config/
RUN rm -r ros2_docker_configs

# Install rustup
RUN curl https://sh.rustup.rs -sSf | sh  -s -- -y
ENV PATH="/home/niklas/.cargo/bin:${PATH}"


# copy ros2_ws and tiago_ws to the home
RUN sudo cp -r /root/tiago_ws /home/niklas
RUN sudo mv /root/ros2_ws  /root/rwu_ws
RUN  sudo cp -r /root/rwu_ws /home/niklas
RUN sudo chown  niklas:niklas -R /home/niklas/rwu_ws/
RUN cd /home/niklas/rwu_ws && rm -rf build/ install/ log/&& source /opt/ros/humble/setup.bash && colcon build
RUN sudo chown  niklas:niklas -R /home/niklas/tiago_ws/
RUN cd /home/niklas/tiago_ws && rm -rf build/ install/ log/ && source /opt/ros/humble/setup.bash && colcon build

RUN sudo apt install ros-humble-rqt-robot-steering -y

RUN echo '#!/bin/bash' > /home/niklas/entrypoint.sh \
 && echo 'exec "$@"' >> /home/niklas/entrypoint.sh \
 && chmod +x /home/niklas/entrypoint.sh
ENTRYPOINT ["/home/niklas/entrypoint.sh"]

