---
services:
  tiago_ws:
    image: tiago_ws
    build:
      context: .
      dockerfile: Dockerfile_Workspace
      args:
        BASE_IMAGE: fbe-dockerreg.rwu.de/prj-iki-ros2/robots/tiago/iki_tiago_base:iki_tiago_core
    environment:
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: /run/user/1000
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
      SIM: true
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /run/user/1000:/run/user/1000
      - ros2_robocup_ws_dev_home:/home/nk-213780
      - $PWD:/home/niklas/ros2_ws/src
      - ./tiago_cyclonedds.xml:/home/nk-213780/tiago_cyclonedds.xml
    # runtime: nvidia
    command: tail -f /dev/null


  tiago_real_ws:
    image: tiago_ws
    build:
      context: .
      dockerfile: Dockerfile_Workspace
      args:
        BASE_IMAGE: fbe-dockerreg.rwu.de/prj-iki-ros2/robots/tiago/iki_tiago_base:iki_tiago_core
    environment:
      ROS_DOMAIN_ID: 66
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: /run/user/1000
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
      CYCLONEDDS_URI: file:///home/nk-213780/tiago_cyclonedds.xml
      SIM: false
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /run/user/1000:/run/user/1000
      - ros2_robocup_ws_dev_home:/home/nk-213780
      - $PWD:/home/niklas/ros2_ws/src
      - ./tiago_cyclonedds.xml:/home/nk-213780/tiago_cyclonedds.xml
    # runtime: nvidia
    command: tail -f /dev/null




  kate_ws:
    image: kate_ws
    build:
      context: .
      dockerfile: Dockerfile_Workspace
      args:
        BASE_IMAGE: fbe-dockerreg.rwu.de/prj-iki-ros2/robots/kate/kate_base:kate_core
    environment:
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: /run/user/1000
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
      SIM: true
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /run/user/1000:/run/user/1000
      - ros2_robocup_ws_dev_home:/home/nk-213780
      - $PWD:/home/niklas/ros2_ws/src
      - ./kate_cyclonedds.xml:/home/nk-213780/kate_cyclonedds.xml
    # runtime: nvidia
    command: tail -f /dev/null

  kate_real_ws:
    image: kate_ws
    build:
      context: .
      dockerfile: Dockerfile_Workspace
      args:
        BASE_IMAGE: fbe-dockerreg.rwu.de/prj-iki-ros2/robots/kate/kate_base:kate_core
    environment:
      ROS_DOMAIN_ID: 77
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: /run/user/1000
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
      CYCLONEDDS_URI: file:///home/nk-213780/kate_cyclonedds.xml
      SIM: false
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /run/user/1000:/run/user/1000
      - ros2_robocup_ws_dev_home:/home/nk-213780
      - $PWD:/home/nk-213780/ros2_ws/src
      - ./kate_cyclonedds.xml:/home/nk-213780/kate_cyclonedds.xml
    # runtime: nvidia
    command: tail -f /dev/null



volumes:
    ros2_robocup_ws_dev_home:  
